// argo--任务模板
export const argo_workflow_template = {
  label_title: "任务模板",
  list_columns: ["id", "name", "describe", "created_by", "created_at"],
  label_columns: {
    images_id: "镜像ID",
    updated_at: "",
    work_dir: "工作目录",
  },
  yh_label: {
    index: "模板分类",
  },
  show_columns: [
    "id",
    "name",
    "describe",
    "version",
    "images_id",
    "hostAliases",
    "work_dir",
    "entrypoint",
    "args",
    "env",
    "volume_mount",
    "privileged",
    "accounts",
    "expand",
    "created_at",
    "updated_at",
  ],
  edit_fieldsets: null,
  add_fieldsets: null,
  edit_columns: [
    {
      name: "images_id",
      label: "镜像",
      description: "",
      validators: [{ type: "DataRequired" }],
      values: null,
      type: "Related",
      required: true,
      default: "",
      "ui-type": "select",
    },
    {
      name: "name",
      label: "名称",
      description: "英文名(小写字母、数字、- 组成)，最长50个字符",
      validators: [
        { type: "Regexp", regex: "^[a-z][a-z0-9-]*[a-z0-9]$" },
        { type: "DataRequired" },
      ],
      values: null,
      type: "String",
      required: true,
      default: "",
      "ui-type": "input",
    },
    {
      name: "version",
      label: "版本",
      description: "job模板的版本，release版本的模板才能被所有用户看到",
      validators: [{ type: "DataRequired" }],
      values: [
        { id: "Alpha", value: "Alpha" },
        { id: "Release", value: "Release" },
      ],
      type: "Select",
      required: true,
      default: "",
      "ui-type": "select",
    },
    {
      name: "describe",
      label: "描述",
      description: "模板的描述将直接显示在pipeline编排界面",
      validators: [{ type: "DataRequired" }],
      values: null,
      type: "String",
      required: false,
      default: "",
      "ui-type": "input",
    },
    {
      name: "work_dir",
      label: "工作目录",
      description: "工作目录，不填写将直接使用镜像默认的工作目录",
      validators: [{ type: "Length", min: null, max: 400 }],
      values: null,
      type: "String",
      required: false,
      default: "",
      "ui-type": "input",
    },
    {
      name: "entrypoint",
      label: "启动命令",
      description:
        "镜像的入口命令，直接写成单行字符串，例如python xx.py，无需添加[]",
      validators: [{ type: "Length", min: null, max: 200 }],
      values: null,
      type: "String",
      required: false,
      default: "",
      "ui-type": "input",
    },
    {
      name: "args",
      label: "启动参数",
      description: "",
      validators: [],
      values: null,
      type: "String",
      required: false,
      default: "",
      "ui-type": "input",
      // "ui-type": "arr_string",
      yh_template: {
        args: {
          args: {
            type: "str",
            label: "参数1",
            default: "",
            describe: "这里是这个参数的描述和备注",
            item_type: "str",
            require: 1,
            range: "",
            placeholder: "",
            editable: 1,
            condition: "",
            choice: [],
          },
        },
      },
      // "ui-type": "textArea",
    },
    {
      name: "resource_cpu",
      label: "CPU申请",
      description: "请输入数字",
      validators: [
        { type: "Regexp", regex: "^[0-9][0-9]*$" },
        { type: "Length", min: 0, max: 200 },
        { type: "DataRequired" },
      ],
      values: null,
      type: "Int",
      required: true,
      default: "0",
      // "ui-type": "input",
      "ui-type": "yh_input",
      yh_in_type: "number",
      yh_out_type: "string",
    },
    {
      name: "resource_memory",
      label: "内存申请",
      description: "请输入数字",
      validators: [
        { type: "Regexp", regex: "^[0-9][0-9]*$" },
        { type: "Length", min: 0, max: 200 },
        { type: "DataRequired" },
      ],
      values: null,
      type: "Int",
      out_type: "String",
      required: true,
      default: "0",
      // "ui-type": "input",
      "ui-type": "yh_input",
      yh_in_type: "number",
      yh_out_type: "string",
    },
    {
      name: "resource_gpu",
      label: "GPU申请",
      description: "请输入数字",
      validators: [
        { type: "Length", min: 0, max: 200 },
        { type: "Regexp", regex: "^[0-9][0-9]*$" },
        { type: "DataRequired" },
      ],
      values: null,
      type: "Int",
      required: false,
      default: "0",
      // "ui-type": "input",
      "ui-type": "yh_input",
      yh_in_type: "number",
      yh_out_type: "string",
    },
    {
      name: "volume_mount",
      label: "挂载目录",
      description: "使用该模板的task，会在添加时，自动添加该挂载。",
      validators: [],
      values: null,
      type: "String",
      required: false,
      default: "",
      "ui-type": "yh_volume_mount",
      yh_template: {
        name: "",
        source: "",
        target: "",
        type: "album-pvc",
        read_only: true,
        disabled: true, // 用来在工作流详情页判断该挂载目录是否可编辑
      },
      yh_data_type: "arr_obj",
      // "ui-type": "file_input",
    },
    {
      name: "env",
      label: "环境变量",
      description: "使用模板的task自动添加的环境变量，支持模板变量。",
      validators: [{ type: "Length", min: null, max: null }],
      values: null,
      type: "String",
      required: false,
      default: "",
      "ui-type": "json_input",
    },
    // {
    //   name: "hostAliases",
    //
    //   label: "host",
    //   description:
    //     "添加到容器内的host映射。<br>书写格式:每行一个dns解析记录，ip host1 host2，<br>示例：1.1.1.1 example1.oa.com example2.oa.com",
    //   validators: [{ type: "Length", min: null, max: null }],
    //
    //   values: null,
    //   type: "String",
    //   required: false,
    //
    //   default: "",
    //
    //
    //   "ui-type": "textArea",
    // },
    {
      name: "privileged",
      label: "特权模式",
      description: "是否启动超级权限",
      validators: null,
      values: [
        { id: 1, value: "yes" },
        { id: 0, value: "no" },
      ],
      type: "Int",
      required: false,
      default: "",
      "ui-type": "radio",
    },
    // {
    //   name: "accounts",
    //
    //   label: "K8s账号",
    //   description:
    //     "k8s的ServiceAccount，在此类任务运行时会自动挂载此账号，多用于模板用于k8s pod/cr时使用",
    //   validators: null,
    //
    //   values: null,
    //   type: "String",
    //   required: false,
    //
    //   default: "",
    //
    //
    //   "ui-type": "input",
    // },
    {
      name: "expand",
      label: "扩展",
      description:
        'json格式的扩展字段，支持 "index":"$模板展示顺序号"，"help_url":"$帮助文档地址"',
      validators: [{ type: "DataRequired" }],
      values: null,
      type: "String",
      required: true,
      default:
        '{\n    "index": -1,\n    "help_url": "https://github.com/tencentmusic/cube-studio"\n}',
      "ui-type": "yh_select_obj",
      yh_template: {
        index: "",
      },
      // "ui-type": "json_input",
    },
  ],
  add_columns: [
    {
      name: "images_id",
      label: "镜像",
      description: "",
      validators: [{ type: "DataRequired" }],
      values: [],
      type: "Related",
      required: true,
      default: "",
      "ui-type": "select",
    },
    {
      name: "name",
      label: "名称",
      description: "英文名(小写字母、数字、- 组成)，最长50个字符",
      validators: [
        { type: "Regexp", regex: "^[a-z][a-z0-9-]*[a-z0-9]$" },
        { type: "Length", min: 1, max: 54 },
        { type: "DataRequired" },
      ],
      values: null,
      type: "String",
      required: true,
      default: "",
      "ui-type": "input",
    },
    {
      name: "version",
      label: "版本",
      description: "job模板的版本，release版本的模板才能被所有用户看到",
      validators: [{ type: "DataRequired" }],
      values: [
        { id: "Alpha", value: "Alpha" },
        { id: "Release", value: "Release" },
      ],
      type: "Select",
      required: true,
      default: "",
      "ui-type": "select",
    },
    {
      name: "describe",
      label: "描述",
      description: "模板的描述将直接显示在pipeline编排界面",
      validators: [{ type: "DataRequired" }],
      values: null,
      type: "String",
      required: true,
      default: "",
      "ui-type": "input",
    },
    {
      name: "work_dir",
      label: "工作目录",
      description: "工作目录，不填写将直接使用镜像默认的工作目录",
      validators: [{ type: "Length", min: null, max: 400 }],
      values: null,
      type: "String",
      required: false,
      default: "",
      "ui-type": "input",
    },
    {
      name: "entrypoint",
      label: "启动命令",
      description:
        "镜像的入口命令，直接写成单行字符串，例如python xx.py，无需添加[]",
      validators: [{ type: "Length", min: null, max: 200 }],
      values: null,
      type: "String",
      required: false,
      default: "",
      "ui-type": "input",
    },
    {
      name: "args",
      label: "启动参数",
      description: "",
      validators: [],
      values: null,
      type: "String",
      required: false,
      default: "",
      "ui-type": "input",
      // "ui-type": "arr_string",
      yh_template: {
        args: {
          args: {
            type: "str",
            label: "参数1",
            default: "",
            describe: "这里是这个参数的描述和备注",
            item_type: "str",
            require: 1,
            range: "",
            placeholder: "",
            editable: 1,
            condition: "",
            choice: [],
          },
        },
      },
      // "ui-type": "textArea",
    },
    {
      name: "resource_cpu",
      label: "CPU申请",
      description: "请输入数字",
      validators: [
        { type: "Regexp", regex: "^[0-9][0-9]*$" },
        { type: "Length", min: 0, max: 200 },
        { type: "DataRequired" },
      ],
      values: null,
      type: "Int",
      required: true,
      default: "0",
      // "ui-type": "input",
      "ui-type": "yh_input",
      yh_in_type: "number",
      yh_out_type: "string",
    },
    {
      name: "resource_memory",
      label: "内存申请",
      description: "请输入数字",
      validators: [
        { type: "Regexp", regex: "^[0-9][0-9]*$" },
        { type: "Length", min: 0, max: 200 },
        { type: "DataRequired" },
      ],
      values: null,
      type: "Int",
      out_type: "String",
      required: true,
      default: "0",
      // "ui-type": "input",
      "ui-type": "yh_input",
      yh_in_type: "number",
      yh_out_type: "string",
    },
    {
      name: "resource_gpu",
      label: "GPU申请",
      description: "请输入数字",
      validators: [
        { type: "Regexp", regex: "^[0-9][0-9]*$" },
        { type: "Length", min: 0, max: 200 },
        { type: "DataRequired" },
      ],
      values: null,
      type: "Int",
      required: true,
      default: "0",
      // "ui-type": "input",
      "ui-type": "yh_input",
      yh_in_type: "number",
      yh_out_type: "string",
    },
    {
      name: "volume_mount",
      label: "挂载目录",
      description: "使用该模板的task，会在添加时，自动添加该挂载。",
      validators: [],
      values: null,
      type: "String",
      required: false,
      default: "",
      "ui-type": "yh_volume_mount",
      yh_template: {
        name: "",
        source: "",
        target: "",
        type: "album-pvc",
        read_only: true,
        disabled: true, // 用来在工作流详情页判断该挂载目录是否可编辑
      },
      yh_data_type: "arr_obj",
      // "ui-type": "file_input",
    },

    {
      name: "env",
      label: "环境变量",
      description: "使用模板的task自动添加的环境变量，支持模板变量。",
      validators: [{ type: "Length", min: null, max: null }],
      values: null,
      type: "String",
      required: false,
      default: "",
      "ui-type": "json_input",
      // "ui-type": "textArea",
    },
    {
      name: "privileged",
      label: "特权模式",
      description: "是否启动超级权限",
      validators: [],
      values: [
        { id: 1, value: "yes" },
        { id: 0, value: "no" },
      ],
      type: "Int",
      required: false,
      default: 0,
      "ui-type": "radio",
    },
    {
      name: "expand",
      label: "扩展",
      description:
        'json格式的扩展字段，支持 "index":"$模板展示顺序号"，"help_url":"$帮助文档地址"',
      validators: [{ type: "DataRequired" }],
      values: null,
      type: "String",
      required: true,
      default:
        '{"index": -1,"help_url": "https://github.com/tencentmusic/cube-studio"}',
      "ui-type": "yh_select_obj",
      yh_template: {
        index: "",
      },
      // "ui-type": "json_input",
    },
  ],
  cols_width: {},
};
export default argo_workflow_template;
