// 项目组--项目分组\模型分组\模板分类
export const project_group = {
  label_title: "dmp_project",
  list_columns: ["id", "name", "describe", "type", "expand"],
  label_columns: {},
  show_columns: [
    "id",
    "name",
    "describe",
    "type",
    "expand",
    "created_by",
    "updated_by",
    "created_at",
    "updated_at",
    "deleted_at",
  ],
  edit_fieldsets: null,
  add_fieldsets: null,
  edit_columns: [
    {
      name: "name",
      label: "名称",
      description: "",
      validators: [
        { type: "Length", min: null, max: 50 },
        { type: "DataRequired" },
      ],
      values: null,
      type: "String",
      required: true,
      default: "",
      "ui-type": "input",
    },
    {
      name: "describe",
      label: "描述",
      description: "",
      validators: [
        { type: "Length", min: null, max: 500 },
        { type: "DataRequired" },
      ],
      values: null,
      type: "String",
      required: true,
      default: "",
      "ui-type": "input",
    },
    {
      name: "expand",
      label: "扩展",
      description: "",
      validators: [{ type: "Length", min: null, max: 65536 }],

      values: null,
      type: "String",
      required: false,
      default: '{\n    "cluster": "dev"\n}',
      "ui-type": "textArea",
    },
  ],
  add_columns: [
    {
      name: "name",
      label: "名称",
      description: "",
      validators: [
        { max: 50, min: null, type: "Length" },
        { type: "DataRequired" },
      ],
      values: null,
      type: "",
      required: true,
      default: "",
      "ui-type": "input",
    },
    {
      name: "describe",
      label: "描述",
      description: "",
      validators: [
        { max: 500, min: null, type: "Length" },
        { type: "DataRequired" },
      ],
      values: null,
      type: "",
      required: true,
      default: "",
      "ui-type": "input",
    },
    {
      name: "type",
      label: "类型",
      description: "",
      validators: [],
      disabled: true,
      values: null,
      type: "",
      required: false,
      default: "",
      "ui-type": "input",
    },
    {
      name: "expand",
      label: "扩展",
      description: "",
      validators: [
        { max: 500, min: null, type: "Length" },
        { type: "DataRequired" },
      ],
      values: null,
      type: "",
      required: false,
      default: "{}",
      "ui-type": "input",
    },
  ],
  cols_width: {
    describe: {
      type: "ellip2",
      width: 200,
    },
    expand: {
      type: "ellip2",
      width: 280,
    },
  },
};
export default project_group;